#version 430 core

layout(local_size_x = 2) in;

struct Particle
{
    vec4 pos_vel;
};

layout(std140, binding = 0) buffer ParticleSSBO {
   Particle particles[ ];
};

// 时间间隔
uniform float deltaTime;

void main()
{
    uint index = gl_GlobalInvocationID.x;  

    Particle particleIn = particles[index];

    particles[index].pos_vel.xy = particleIn.pos_vel.xy + particleIn.pos_vel.zw * deltaTime;
}