#version 430 core

layout(local_size_x = 1) in;

struct Particle
{
    vec4 pos_vel_et;
};

layout(std140, binding = 0) buffer ParticleSSBO {
   Particle particles[ ];
};

uniform float deltaTime;

void main()
{
    uint index = gl_GlobalInvocationID.x;  
    Particle particleIn = particles[index];

    float v = particleIn.pos_vel_et.z;      // 速度（竖直向下的速度）
    float t = deltaTime;                    // 时间（距离上一帧的时间）
    float g = .98;                          // 重力加速度
    float h = particleIn.pos_vel_et.y;      // 位置（高度）
    float e = particleIn.pos_vel_et.w;      // 弹性系数

    h = h - v * t - 0.5 * g * t * t;
    v = v + g * t;

    // 运动到屏幕最下面时弹起
    if(h < -1.0)
    {
        h = -2.0 - h;
        v = -e * v; 
    }

    // 注意此处不能直接对 particleIn 赋值
    particles[index].pos_vel_et.y = h;
    particles[index].pos_vel_et.z = v;
}