#version 430 core

// 本地工作组的大小，不能小于顶点的个数，如果小于则改变的顶点个数就会少于实际的顶点个数
// 本例共3个顶点，所以此处填3（全局工作组大小为{1,1,1}）
layout(local_size_x = 3) in;

layout(rgba32f, binding = 0) uniform imageBuffer position_buffer;

uniform float offset;

void main()
{
    // gl_GlobalInvocationID可以简单理解为第几个顶点，可能的值为：0、1、2
    vec4 pos = imageLoad(position_buffer, int(gl_GlobalInvocationID.x));

    // 给输入的顶点在x分量增加一个偏移值，并将新的顶点输出
    pos += vec4(offset, 0.0, 0.0, 0.0);
    
    imageStore(position_buffer, int(gl_GlobalInvocationID.x), pos);
}
